// GitbubBranch name change ---------
// igthub repo url değişkene ata -------
//  workingDirectory : ""
// hangi bracnhten zipleniyorsa onun adı yazsın -------
// parametreleri farklı bir biçimde düzenle
def VirtualMachines = [
       test: [
         host: [
            [
                name: 'test',
                host: '3.75.224.143',
                user: '',
                identityFile: '',
                allowAnyHosts: true,
                portNumber: 10000
            ]
        ],
        gitBranchName: "test",
       ]
]

def VirtualMachinesEnvironment = VirtualMachines.keySet().toList();
def selectedEnvironment = VirtualMachines[parameters]

pipeline {
    agent any
    
    parameters {
        choice choices: VirtualMachinesEnvironment, description: 'this is a description', name: 'parameters'
        
    }

    environment {
        APP_DIR = 'jenkinsapp'
        ZIP_FILE_NAME = "jenkinsapp_${BUILD_NUMBER}_${selectedEnvironment.gitBranchName}.zip"
        S3_BUCKET = 'jenkinsfastapi'
        GITHUB_URL = 'https://github.com/erdemdoganayy/fastapi-jenkins'
    }
    stages {
    

        stage('Remote SSH') {
            steps {
                script {
                 withCredentials([sshUserPrivateKey(credentialsId: 'aws-flask-machine', keyFileVariable: 'KEY', usernameVariable: 'USERNAME')])
                    {
                        for (server in selectedEnvironment.host) {
                            server.user = USERNAME
                            server.identityFile = KEY

                            echo USERNAME
                            echo KEY
                        
                            stage("${server.name} - Repo Put To VM") {

                                // SSH PUT İLE JENKİNS WORKSPACE DİZİNİNDEKİ İNDİRİLEN REPOYU KARŞI SUNUCUYA AKTARIYOR || AKTARILMIŞ DOSYANIN ADINI DEĞİŞTİRİP ESKİSİNİ SİLİYOR
                               
                                sshCommand failOnError: true, remote: server, command: "echo 'sa'"
                          

                            }
        
  
                     
                        }
                    }
                }
            }
        }
    }
}
