def buildNumber = currentBuild.number
pipeline {
    agent any
    environment {
        BUILD_NUMBER = buildNumber
        FILE_PATH = '/var/lib/jenkins/workspace/task-jenkins/hermit'
        ZIP_FILE_NAME = "examples_${BUILD_NUMBER}.zip"
        SOURCE_DIR = 'examples'
        S3_BUCKET = 'myjnknsbckt'
        AWS_CLI_PATH = '/usr/local/bin/aws'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
        stages {
            stage('Github Repo Clone') {
                steps {
                // sh 'rm -rf $cloneFolderName'
                // sh 'git clone https://github.com/facebookexperimental/hermit'
                // checkout scmGit(
                // branches: [[name: '*/main']],
                // extensions: [],
                // userRemoteConfigs: [[url: 'https://github.com/facebookexperimental/hermit']])
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/facebookexperimental/hermit']]])
                }
            }
            stage('Github Repo ZIP') {
                steps {
                    script {
                        dir("${env.FILE_PATH}") {
                        sh "zip -r ${env.ZIP_FILE_NAME} ${env.SOURCE_DIR}"
                        sh "cp -R ${env.ZIP_FILE_NAME} ../buckets/${env.ZIP_FILE_NAME}"
                        }
                    }
                }
            }

            stage('Upload Aws S3') {
                steps {
                script {
                            sh " ${env.AWS_CLI_PATH} s3 cp /var/lib/jenkins/workspace/task-jenkins/buckets/examples_${env.BUILD_NUMBER}.zip s3://${env.S3_BUCKET}/ "
                        }
                }
            }
            stage('Clean Up') {
                steps {
                script {
                        sh "rm -rf buckets/examples_${env.ZIP_FILE_NAME}.zip "
                }
                }
            }
        }
}
