def filePath = '/var/lib/jenkins/workspace/nginx-demo/nginx-hello'
def triggerPipeline = 'nginx-demo-dive-analyze'
pipeline {
    agent any
    environment {
        DOCKER_REPO = "jrdeveloper06/nginx_hello"
    }
        stages {
            stage('Checkout & Github Repo Clone') {
                steps  {
                checkout changelog: false,
                         scm: scmGit(userRemoteConfigs: [
                         [ credentialsId: 'my-github-id',
                           url: 'https://github.com/erdemdoganayy/nginx-demos' ]
                         ])
                }
            }
        stage('Docker Build & Push') {
             steps  {
                 script {
                 withCredentials([
                 string(credentialsId: 'DOCKER_USERNAME', variable: 'DOCKER_USERNAME'),
                 string(credentialsId: 'DOCKER_PASSWORD', variable: 'DOCKER_PASSWORD')
                 ]) {
                     // Docker Build
                     sh "docker build -t nginx_hello:${BUILD_NUMBER} ${filePath}"
                     // Docker Push
                     sh "docker tag nginx_hello ${env.DOCKER_REPO}:${BUILD_NUMBER}"
                     sh "docker push ${env.DOCKER_REPO}:${BUILD_NUMBER}"
                 }
                 }
             }
        }
        stage("Clean Up") {
            steps {
                sh "docker image rm nginx_hello:${BUILD_NUMBER}"
                sh "docker image rm ${env.DOCKER_REPO}:${BUILD_NUMBER}"
            }
        }
        stage('Deploy') {
                steps {
                build job: "${triggerPipeline}", parameters: [string(name: 'DOCKERTAG_BUILD_NUMBER', value: "${currentBuild.number}")]
                }
        }
        }
}
